# app_config.yml
app_name: BACHUETECH AI-UI
version: 1
environment: dev

dev:
  enc_key: cmttu9zvbR30FGi99zKvq2PxCn1A3b8x4AJej2r+3m54-pRsFjdFFzpyqQsiqmSx
  files_app_dir: site
  app_path: /ai/app
  api_path: /ai/api/
  end_points:
    - id: chat
      path: /chat
    - id: prompt
      path: /prompt
    - id: models
      path: /models